import { Comic } from '@/src/types/comic';

export const images = {
  cover: require('./images/alien_cover.png'),
  p1: require('./images/alien_p1.png'),
  p1_s1: require('./images/alien_p1_s1.png'),
  p1_s2: require('./images/alien_p1_s2.png'),
  p1_s3: require('./images/alien_p1_s3.png'),
  p2: require('./images/alien_p2.png'),
  p2_s1: require('./images/alien_p2_s1.png'),
  p2_s2: require('./images/alien_p2_s2.png'),
  p2_s3: require('./images/alien_p2_s3.png'),
  p2_s4: require('./images/alien_p2_s4.png'),
  p3: require('./images/alien_p3.png'),
  p3_s1: require('./images/alien_p3_s1.png'),
  p3_s2: require('./images/alien_p3_s2.png'),
  p3_s3: require('./images/alien_p3_s3.png'),
  p4: require('./images/alien_p4.png'),
  p4_s1: require('./images/alien_p4_s1.png'),
  p4_s2: require('./images/alien_p4_s2.png'),
  p4_s3: require('./images/alien_p4_s3.png'),
  p5: require('./images/alien_p5.png'),
  p5_s1: require('./images/alien_p5_s1.png'),
  p5_s2: require('./images/alien_p5_s2.png'),
  p5_s3: require('./images/alien_p5_s3.png'),
  p5_s4: require('./images/alien_p5_s4.png'),
  p6: require('./images/alien_p6.png'),
  p6_s1: require('./images/alien_p6_s1.png'),
  p6_s2: require('./images/alien_p6_s2.png'),
  p6_s3: require('./images/alien_p6_s3.png'),
  p6_s4: require('./images/alien_p6_s4.png'),
};

export const audio = {
  cover: require('./audio/alien_cover.mp3'),
  p1_s1: require('./audio/alien_p1_s1.mp3'),
  p1_s2: require('./audio/alien_p1_s2.mp3'),
  p2_s2: require('./audio/alien_p2_s2.mp3'),
  p2_s3: require('./audio/alien_p2_s3.mp3'),
  p2_s4: require('./audio/alien_p2_s4.mp3'),
  p3_s1: require('./audio/alien_p3_s1.mp3'),
  p3_s2: require('./audio/alien_p3_s2.mp3'),
  p3_s3: require('./audio/alien_p3_s3.mp3'),
  p4_s1: require('./audio/alien_p4_s1.mp3'),
  p4_s2: require('./audio/alien_p4_s2.mp3'),
  p4_s3: require('./audio/alien_p4_s3.mp3'),
  p5_s1: require('./audio/alien_p5_s1.mp3'),
  p5_s2: require('./audio/alien_p5_s2.mp3'),
  p5_s3: require('./audio/alien_p5_s3.mp3'),
  p5_s4: require('./audio/alien_p5_s4.mp3'),
  p6_s2: require('./audio/alien_p6_s2.mp3'),
  p6_s3: require('./audio/alien_p6_s3.mp3'),
  p6_s4: require('./audio/alien_p6_s4.mp3'),
};

export const comic: Comic = {
  id: 'comic-alien',
  title: 'El Visitante',
  description: 'Mía encounters a friendly alien named Zik who got lost while learning Spanish. A beginner-friendly story about helping others.',
  coverImage: 'local:alien_cover',
  level: 'beginner',
  isPremium: false,
  reviewWords: [
    {
      word: { id: 'a4', text: 'noche', meaning: 'night', baseForm: 'noche' },
      panelId: 'alien-panel-1-1',
      pageId: 'alien-page-1',
    },
    {
      word: { id: 'a5', text: 'qué', meaning: 'what', baseForm: 'qué' },
      panelId: 'alien-panel-1-2',
      pageId: 'alien-page-1',
    },
    {
      word: { id: 'a9', text: 'quién', meaning: 'who', baseForm: 'quién' },
      panelId: 'alien-panel-2-2',
      pageId: 'alien-page-2',
    },
    {
      word: { id: 'a12', text: 'me llamo', meaning: 'my name is / I call myself', baseForm: 'llamarse', audioUrl: 'phrase:me_llamo' },
      panelId: 'alien-panel-2-3',
      pageId: 'alien-page-2',
    },
    {
      word: { id: 'a21', text: 'bien', meaning: 'good, well', baseForm: 'bien' },
      panelId: 'alien-panel-3-1',
      pageId: 'alien-page-3',
    },
    {
      word: { id: 'a23', text: 'tengo', meaning: 'I have', baseForm: 'tener' },
      panelId: 'alien-panel-3-2',
      pageId: 'alien-page-3',
    },
    {
      word: { id: 'a26', text: 'dónde', meaning: 'where', baseForm: 'dónde' },
      panelId: 'alien-panel-3-3',
      pageId: 'alien-page-3',
    },
    {
      word: { id: 'a51', text: 'hablo', meaning: 'I speak', baseForm: 'hablar' },
      panelId: 'alien-panel-5-3',
      pageId: 'alien-page-5',
    },
    {
      word: { id: 'a67', text: 'la casa', meaning: 'the house', baseForm: 'casa', audioUrl: 'phrase:la_casa' },
      panelId: 'alien-panel-5-4',
      pageId: 'alien-page-5',
    },
  ],
  pages: [
    {
      id: 'alien-page-cover',
      pageNumber: 1,
      masterImage: 'local:alien_cover',
      panels: [
        {
          id: 'alien-panel-cover',
          artworkImage: 'local:alien_cover',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 1,
          bubbles: [
            {
              id: 'alien-bubble-cover',
              type: 'narration',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s-cover',
                  text: 'El Visitante',
                  translation: 'The Visitor',
                  audioUrl: 'local:alien_cover',
                  words: [
                    { id: 'a-cover-1', text: 'El', meaning: 'The (masculine)', baseForm: 'el' },
                    { id: 'a-cover-2', text: 'Visitante', meaning: 'Visitor', baseForm: 'visitante' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'alien-page-1',
      pageNumber: 2,
      masterImage: 'local:alien_p1',
      panels: [
        {
          id: 'alien-panel-1-1',
          artworkImage: 'local:alien_p1_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.38,
          bubbles: [
            {
              id: 'alien-bubble-1-1-1',
              type: 'narration',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s1-1',
                  text: 'Tarde en la noche',
                  translation: 'Late at night',
                  audioUrl: 'local:alien_p1_s1',
                  words: [
                    { id: 'a1', text: 'Tarde', meaning: 'Late', baseForm: 'tarde', startTimeMs: 119, endTimeMs: 519 },
                    { id: 'a2', text: 'en', meaning: 'in, at', baseForm: 'en', startTimeMs: 540, endTimeMs: 639 },
                    { id: 'a3', text: 'la', meaning: 'the (feminine)', baseForm: 'la', startTimeMs: 680, endTimeMs: 719 },
                    { id: 'a4', text: 'noche', meaning: 'night', baseForm: 'noche', startTimeMs: 779, endTimeMs: 1179 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-1-2',
          artworkImage: 'local:alien_p1_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.38,
          tapZoneWidth: 1,
          tapZoneHeight: 0.32,
          bubbles: [
            {
              id: 'alien-bubble-1-2-1',
              type: 'thought',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s1-2',
                  text: '¿Qué fue eso..?',
                  translation: 'What was that..?',
                  audioUrl: 'local:alien_p1_s2',
                  words: [
                    { id: 'a5', text: '¿Qué', meaning: 'What', baseForm: 'qué', startTimeMs: 119, endTimeMs: 399 },
                    { id: 'a6', text: 'fue', meaning: 'was (ser/ir past)', baseForm: 'ser', startTimeMs: 419, endTimeMs: 680 },
                    { id: 'a7', text: 'eso..?', meaning: 'that', baseForm: 'eso', startTimeMs: 679, endTimeMs: 1660 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-1-3',
          artworkImage: 'local:alien_p1_s3',
          panelOrder: 3,
          tapZoneX: 0,
          tapZoneY: 0.69,
          tapZoneWidth: 1,
          tapZoneHeight: 0.31,
          bubbles: [],
        },
      ],
    },
    {
      id: 'alien-page-2',
      pageNumber: 3,
      masterImage: 'local:alien_p2',
      panels: [
        {
          id: 'alien-panel-2-1',
          artworkImage: 'local:alien_p2_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.36,
          bubbles: [],
        },
        {
          id: 'alien-panel-2-2',
          artworkImage: 'local:alien_p2_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.35,
          tapZoneWidth: 1,
          tapZoneHeight: 0.32,
          bubbles: [
            {
              id: 'alien-bubble-2-2-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s2-2',
                  text: '¿Qué...? ¿Quién eres?',
                  translation: 'What...? Who are you?',
                  audioUrl: 'local:alien_p2_s2',
                  words: [
                    { id: 'a8', text: '¿Qué...?', meaning: 'What', baseForm: 'qué', startTimeMs: 140, endTimeMs: 500 },
                    { id: 'a9', text: '¿Quién', meaning: 'Who', baseForm: 'quién', startTimeMs: 939, endTimeMs: 1179 },
                    { id: 'a10', text: 'eres?', meaning: 'are you (ser)', baseForm: 'ser', startTimeMs: 1259, endTimeMs: 1579 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-2-3',
          artworkImage: 'local:alien_p2_s3',
          panelOrder: 3,
          tapZoneX: 0,
          tapZoneY: 0.67,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.33,
          bubbles: [
            {
              id: 'alien-bubble-2-3-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s2-3',
                  text: 'Me llamo Zik. ¿Cómo te llamas?',
                  translation: "My name is Zik. What's your name?",
                  audioUrl: 'local:alien_p2_s3',
                  words: [
                    { id: 'a11', text: 'Me', meaning: 'Myself (reflexive)', baseForm: 'me', startTimeMs: 199, endTimeMs: 339 },
                    { id: 'a12', text: 'llamo', meaning: 'I call / am called', baseForm: 'llamarse', startTimeMs: 379, endTimeMs: 680 },
                    { id: 'a13', text: 'Zik.', meaning: 'Zik (name)', baseForm: 'Zik', startTimeMs: 759, endTimeMs: 1199 },
                    { id: 'a14', text: '¿Cómo', meaning: 'How', baseForm: 'cómo', startTimeMs: 1579, endTimeMs: 1819 },
                    { id: 'a15', text: 'te', meaning: 'yourself (reflexive)', baseForm: 'te', startTimeMs: 1839, endTimeMs: 1960 },
                    { id: 'a16', text: 'llamas?', meaning: 'do you call yourself', baseForm: 'llamarse', startTimeMs: 1979, endTimeMs: 2539 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-2-4',
          artworkImage: 'local:alien_p2_s4',
          panelOrder: 4,
          tapZoneX: 0.5,
          tapZoneY: 0.67,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.33,
          bubbles: [
            {
              id: 'alien-bubble-2-4-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s2-4',
                  text: 'Me llamo Mía.',
                  translation: 'My name is Mía.',
                  audioUrl: 'local:alien_p2_s4',
                  words: [
                    { id: 'a17', text: 'Me', meaning: 'Myself (reflexive)', baseForm: 'me', startTimeMs: 119, endTimeMs: 259 },
                    { id: 'a18', text: 'llamo', meaning: 'I call / am called', baseForm: 'llamarse', startTimeMs: 339, endTimeMs: 679 },
                    { id: 'a19', text: 'Mía.', meaning: 'Mía (name)', baseForm: 'Mía', startTimeMs: 679, endTimeMs: 1740 },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'alien-page-3',
      pageNumber: 4,
      masterImage: 'local:alien_p3',
      panels: [
        {
          id: 'alien-panel-3-1',
          artworkImage: 'local:alien_p3_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.999,
          bubbles: [
            {
              id: 'alien-bubble-3-1-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s3-1',
                  text: '¿Estás bien?',
                  translation: 'Are you okay?',
                  audioUrl: 'local:alien_p3_s1',
                  words: [
                    { id: 'a20', text: '¿Estás', meaning: 'Are you (temporary state)', baseForm: 'estar', startTimeMs: 119, endTimeMs: 599 },
                    { id: 'a21', text: 'bien?', meaning: 'well, okay', baseForm: 'bien', startTimeMs: 599, endTimeMs: 1579 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-3-2',
          artworkImage: 'local:alien_p3_s2',
          panelOrder: 2,
          tapZoneX: 0.5,
          tapZoneY: 0.0,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.56,
          bubbles: [
            {
              id: 'alien-bubble-3-2-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s3-2',
                  text: 'Yo... tengo miedo.',
                  translation: "I... I'm scared. (I have fear = I am scared)",
                  audioUrl: 'local:alien_p3_s2',
                  words: [
                    { id: 'a22', text: 'Yo...', meaning: 'I', baseForm: 'yo', startTimeMs: 119, endTimeMs: 560 },
                    { id: 'a23', text: 'tengo', meaning: 'I have', baseForm: 'tener', startTimeMs: 859, endTimeMs: 1120 },
                    { id: 'a24', text: 'miedo.', meaning: 'fear (I have fear = I am scared)', baseForm: 'miedo', startTimeMs: 1180, endTimeMs: 1499 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-3-3',
          artworkImage: 'local:alien_p3_s3',
          panelOrder: 3,
          tapZoneX: 0.5,
          tapZoneY: 0.56,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.44,
          bubbles: [
            {
              id: 'alien-bubble-3-3-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s3-3',
                  text: '¿De dónde eres?',
                  translation: 'Where are you from?',
                  audioUrl: 'local:alien_p3_s3',
                  words: [
                    { id: 'a25', text: '¿De', meaning: 'From', baseForm: 'de', startTimeMs: 119, endTimeMs: 319 },
                    { id: 'a26', text: 'dónde', meaning: 'where', baseForm: 'dónde', startTimeMs: 339, endTimeMs: 619 },
                    { id: 'a27', text: 'eres?', meaning: 'are you (ser - origin)', baseForm: 'ser', startTimeMs: 659, endTimeMs: 1100 },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'alien-page-4',
      pageNumber: 5,
      masterImage: 'local:alien_p4',
      panels: [
        {
          id: 'alien-panel-4-1',
          artworkImage: 'local:alien_p4_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.48,
          bubbles: [
            {
              id: 'alien-bubble-4-1-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s4-1',
                  text: 'Vengo de Zizark.',
                  translation: "I'm from Zizark.",
                  audioUrl: 'local:alien_p4_s1',
                  words: [
                    { id: 'a28', text: 'Vengo', meaning: 'I come', baseForm: 'venir', startTimeMs: 140, endTimeMs: 539 },
                    { id: 'a29', text: 'de', meaning: 'from', baseForm: 'de', startTimeMs: 539, endTimeMs: 719 },
                    { id: 'a30', text: 'Zizark.', meaning: 'Zizark (planet name)', baseForm: 'Zizark', startTimeMs: 759, endTimeMs: 1340 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-4-2',
          artworkImage: 'local:alien_p4_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.48,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.52,
          bubbles: [
            {
              id: 'alien-bubble-4-2-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s4-2',
                  text: '¿Zizark? ¿Dónde está eso?',
                  translation: 'Zizark? Where is that?',
                  audioUrl: 'local:alien_p4_s2',
                  words: [
                    { id: 'a31', text: '¿Zizark?', meaning: 'Zizark (planet name)', baseForm: 'Zizark', startTimeMs: 259, endTimeMs: 2000 },
                    { id: 'a32', text: '¿Dónde', meaning: 'Where', baseForm: 'dónde', startTimeMs: 1999, endTimeMs: 2379 },
                    { id: 'a33', text: 'está', meaning: 'is (location)', baseForm: 'estar', startTimeMs: 2539, endTimeMs: 2700 },
                    { id: 'a34', text: 'eso?', meaning: 'that', baseForm: 'eso', startTimeMs: 2740, endTimeMs: 3179 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-4-3',
          artworkImage: 'local:alien_p4_s3',
          panelOrder: 3,
          tapZoneX: 0.5,
          tapZoneY: 0.48,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.52,
          bubbles: [
            {
              id: 'alien-bubble-4-3-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s4-3',
                  text: 'Es un planeta.',
                  translation: "It's a planet.",
                  audioUrl: 'local:alien_p4_s3',
                  words: [
                    { id: 'a35', text: 'Es', meaning: 'It is (ser)', baseForm: 'ser', startTimeMs: 79, endTimeMs: 379 },
                    { id: 'a36', text: 'un', meaning: 'a (masculine)', baseForm: 'un', startTimeMs: 479, endTimeMs: 679 },
                    { id: 'a37', text: 'planeta.', meaning: 'planet', baseForm: 'planeta', startTimeMs: 699, endTimeMs: 1419 },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'alien-page-5',
      pageNumber: 6,
      masterImage: 'local:alien_p5',
      panels: [
        {
          id: 'alien-panel-5-1',
          artworkImage: 'local:alien_p5_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.49,
          bubbles: [
            {
              id: 'alien-bubble-5-1-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s5-1',
                  text: '¿Un planeta? ¿Por qué viniste aquí?',
                  translation: 'A planet? Why did you come here?',
                  audioUrl: 'local:alien_p5_s1',
                  words: [
                    { id: 'a38', text: '¿Un', meaning: 'A (masculine)', baseForm: 'un', startTimeMs: 199, endTimeMs: 459 },
                    { id: 'a39', text: 'planeta?', meaning: 'planet', baseForm: 'planeta', startTimeMs: 479, endTimeMs: 2159 },
                    { id: 'a40', text: '¿Por', meaning: 'For, because of', baseForm: 'por', startTimeMs: 2219, endTimeMs: 2339 },
                    { id: 'a41', text: 'qué', meaning: 'what (por qué = why)', baseForm: 'qué', startTimeMs: 2419, endTimeMs: 2500 },
                    { id: 'a42', text: 'viniste', meaning: 'did you come (venir past)', baseForm: 'venir', startTimeMs: 2539, endTimeMs: 2899 },
                    { id: 'a43', text: 'aquí?', meaning: 'here', baseForm: 'aquí', startTimeMs: 2919, endTimeMs: 4460 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-5-2',
          artworkImage: 'local:alien_p5_s2',
          panelOrder: 2,
          tapZoneX: 0.5,
          tapZoneY: 0.0,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.49,
          bubbles: [
            {
              id: 'alien-bubble-5-2-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s5-2',
                  text: 'Por accidente. Me perdí.',
                  translation: 'By accident. I got lost.',
                  audioUrl: 'local:alien_p5_s2',
                  words: [
                    { id: 'a44', text: 'Por', meaning: 'By, because of', baseForm: 'por', startTimeMs: 99, endTimeMs: 279 },
                    { id: 'a45', text: 'accidente.', meaning: 'accident', baseForm: 'accidente', startTimeMs: 319, endTimeMs: 999 },
                    { id: 'a46', text: 'Me', meaning: 'Myself (reflexive)', baseForm: 'me', startTimeMs: 1439, endTimeMs: 1620 },
                    { id: 'a47', text: 'perdí.', meaning: 'I got lost (perderse past)', baseForm: 'perderse', startTimeMs: 1639, endTimeMs: 2139 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-5-3',
          artworkImage: 'local:alien_p5_s3',
          panelOrder: 3,
          tapZoneX: 0,
          tapZoneY: 0.48,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.52,
          bubbles: [
            {
              id: 'alien-bubble-5-3-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s5-3',
                  text: '¿Puedes ayudarme? Solo hablo un poco de español. Estoy aprendiendo.',
                  translation: "Can you help me? I only speak a little Spanish. I'm learning.",
                  audioUrl: 'local:alien_p5_s3',
                  words: [
                    { id: 'a48', text: '¿Puedes', meaning: 'Can you (poder)', baseForm: 'poder', startTimeMs: 99, endTimeMs: 579 },
                    { id: 'a49', text: 'ayudarme?', meaning: 'help me', baseForm: 'ayudar', startTimeMs: 699, endTimeMs: 1680 },
                    { id: 'a50', text: 'Solo', meaning: 'Only', baseForm: 'solo', startTimeMs: 1860, endTimeMs: 2119 },
                    { id: 'a51', text: 'hablo', meaning: 'I speak', baseForm: 'hablar', startTimeMs: 2200, endTimeMs: 2459 },
                    { id: 'a52', text: 'un', meaning: 'a', baseForm: 'un', startTimeMs: 2480, endTimeMs: 2659 },
                    { id: 'a53', text: 'poco', meaning: 'little', baseForm: 'poco', startTimeMs: 2659, endTimeMs: 2960 },
                    { id: 'a54', text: 'de', meaning: 'of', baseForm: 'de', startTimeMs: 2960, endTimeMs: 3039 },
                    { id: 'a55', text: 'español.', meaning: 'Spanish', baseForm: 'español', startTimeMs: 3079, endTimeMs: 3860 },
                    { id: 'a56', text: 'Estoy', meaning: 'I am (temporary)', baseForm: 'estar', startTimeMs: 3939, endTimeMs: 4339 },
                    { id: 'a57', text: 'aprendiendo.', meaning: 'learning', baseForm: 'aprender', startTimeMs: 4360, endTimeMs: 5179 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-5-4',
          artworkImage: 'local:alien_p5_s4',
          panelOrder: 4,
          tapZoneX: 0.5,
          tapZoneY: 0.48,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.52,
          bubbles: [
            {
              id: 'alien-bubble-5-4-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s5-4',
                  text: '¡Claro! No te preocupes, te ayudaré. Vamos a la casa.',
                  translation: "Of course! Don't worry, I'll help you. Let's go to the house.",
                  audioUrl: 'local:alien_p5_s4',
                  words: [
                    { id: 'a58', text: '¡Claro!', meaning: 'Of course!', baseForm: 'claro', startTimeMs: 119, endTimeMs: 860 },
                    { id: 'a59', text: 'No', meaning: 'No, not', baseForm: 'no', startTimeMs: 899, endTimeMs: 979 },
                    { id: 'a60', text: 'te', meaning: 'yourself', baseForm: 'te', startTimeMs: 1019, endTimeMs: 1079 },
                    { id: 'a61', text: 'preocupes,', meaning: "worry (don't worry)", baseForm: 'preocuparse', startTimeMs: 1139, endTimeMs: 1799 },
                    { id: 'a62', text: 'te', meaning: 'you (indirect object)', baseForm: 'te', startTimeMs: 1819, endTimeMs: 1879 },
                    { id: 'a63', text: 'ayudaré.', meaning: 'I will help', baseForm: 'ayudar', startTimeMs: 1940, endTimeMs: 2819 },
                    { id: 'a64', text: 'Vamos', meaning: "Let's go", baseForm: 'ir', startTimeMs: 2839, endTimeMs: 3059 },
                    { id: 'a65', text: 'a', meaning: 'to', baseForm: 'a', startTimeMs: 3079, endTimeMs: 3119 },
                    { id: 'a66', text: 'la', meaning: 'the (feminine)', baseForm: 'la', startTimeMs: 3139, endTimeMs: 3259 },
                    { id: 'a67', text: 'casa.', meaning: 'house', baseForm: 'casa', startTimeMs: 3279, endTimeMs: 3579 },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'alien-page-6',
      pageNumber: 7,
      masterImage: 'local:alien_p6',
      panels: [
        {
          id: 'alien-panel-6-1',
          artworkImage: 'local:alien_p6_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.31,
          bubbles: [],
        },
        {
          id: 'alien-panel-6-2',
          artworkImage: 'local:alien_p6_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.31,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.30,
          bubbles: [
            {
              id: 'alien-bubble-6-2-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s6-2',
                  text: '¿Qué está pasando?',
                  translation: "What's happening?",
                  audioUrl: 'local:alien_p6_s2',
                  words: [
                    { id: 'a68', text: '¿Qué', meaning: 'What', baseForm: 'qué', startTimeMs: 79, endTimeMs: 179 },
                    { id: 'a69', text: 'está', meaning: 'is (estar)', baseForm: 'estar', startTimeMs: 179, endTimeMs: 359 },
                    { id: 'a70', text: 'pasando?', meaning: 'happening', baseForm: 'pasar', startTimeMs: 360, endTimeMs: 1019 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-6-3',
          artworkImage: 'local:alien_p6_s3',
          panelOrder: 3,
          tapZoneX: 0.5,
          tapZoneY: 0.31,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.30,
          bubbles: [
            {
              id: 'alien-bubble-6-3-1',
              type: 'speech',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s6-3',
                  text: 'Hemos venido a tomar el control.',
                  translation: "We've come to take control.",
                  audioUrl: 'local:alien_p6_s3',
                  words: [
                    { id: 'a71', text: 'Hemos', meaning: 'We have (auxiliary)', baseForm: 'haber', startTimeMs: 119, endTimeMs: 740 },
                    { id: 'a72', text: 'venido', meaning: 'come (past participle)', baseForm: 'venir', startTimeMs: 759, endTimeMs: 1559 },
                    { id: 'a73', text: 'a', meaning: 'to', baseForm: 'a', startTimeMs: 1579, endTimeMs: 1879 },
                    { id: 'a74', text: 'tomar', meaning: 'to take', baseForm: 'tomar', startTimeMs: 1899, endTimeMs: 2400 },
                    { id: 'a75', text: 'el', meaning: 'the (masculine)', baseForm: 'el', startTimeMs: 2460, endTimeMs: 2660 },
                    { id: 'a76', text: 'control.', meaning: 'control', baseForm: 'control', startTimeMs: 2679, endTimeMs: 3339 },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'alien-panel-6-4',
          artworkImage: 'local:alien_p6_s4',
          panelOrder: 4,
          tapZoneX: 0,
          tapZoneY: 0.60,
          tapZoneWidth: 1,
          tapZoneHeight: 0.39,
          bubbles: [
            {
              id: 'alien-bubble-6-4-1',
              type: 'thought',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'alien-s6-4',
                  text: 'Oh... solo era un sueño...',
                  translation: 'Oh... it was just a dream...',
                  audioUrl: 'local:alien_p6_s4',
                  words: [
                    { id: 'a77', text: 'Oh...', meaning: 'Oh (interjection)', baseForm: 'oh', startTimeMs: 99, endTimeMs: 819 },
                    { id: 'a78', text: 'solo', meaning: 'only, just', baseForm: 'solo', startTimeMs: 919, endTimeMs: 1200 },
                    { id: 'a79', text: 'era', meaning: 'it was (ser imperfect)', baseForm: 'ser', startTimeMs: 1199, endTimeMs: 1320 },
                    { id: 'a80', text: 'un', meaning: 'a', baseForm: 'un', startTimeMs: 1319, endTimeMs: 1499 },
                    { id: 'a81', text: 'sueño...', meaning: 'dream', baseForm: 'sueño', startTimeMs: 1519, endTimeMs: 1899 },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
