import { Comic } from '@/src/types/comic';

export const images = {
  p1: require('./images/horror_test_p1.png'),
  p2: require('./images/horror_test_p2.jpg'),
  p3: require('./images/horror_test_p3.jpg'),
  p4: require('./images/horror_test_p4.jpg'),
  p1_s1: require('./images/horror_test_p1_s1.png'),
  p1_s2: require('./images/horror_test_p1_s2.png'),
  p1_s3: require('./images/horror_test_p1_s3.png'),
  p2_s1: require('./images/horror_test_p2_s1.png'),
  p2_s2: require('./images/horror_test_p2_s2.png'),
  p3_s1: require('./images/horror_test_p3_s1.png'),
  p3_s2: require('./images/horror_test_p3_s2.png'),
  p3_s3: require('./images/horror_test_p3_s3.png'),
  p4_s1: require('./images/horror_test_p4_s1.png'),
  p4_s2: require('./images/horror_test_p4_s2.png'),
  p4_s3: require('./images/horror_test_p4_s3.png'),
};

export const audio = {};

export const comic: Comic = {
  id: 'comic-horror',
  title: 'El Fin del Mundo',
  description: 'A survivor searches for shelter in a post-apocalyptic world. Learn vocabulary related to survival, fear, and hope.',
  coverImage: 'local:horror_p1',
  level: 'intermediate',
  isPremium: false,
  pages: [
    {
      id: 'horror-page-1',
      pageNumber: 1,
      masterImage: 'local:horror_p1',
      panels: [
        {
          id: 'horror-panel-1-1',
          artworkImage: 'local:horror_p1_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.47,
          bubbles: [
            {
              id: 'horror-bubble-1-1-1',
              type: 'narration',
              positionX: 0.1,
              positionY: 0.1,
              width: 0.8,
              height: 0.15,
              sentences: [
                {
                  id: 'horror-s1',
                  text: 'Tres años después del comienzo del fin.',
                  translation: 'Three years after the beginning of the end.',
                  words: [
                    { id: 'h1', text: 'Tres', meaning: 'Three', baseForm: 'tres' },
                    { id: 'h2', text: 'años', meaning: 'years', baseForm: 'año' },
                    { id: 'h3', text: 'después', meaning: 'after', baseForm: 'después' },
                    { id: 'h4', text: 'del', meaning: 'of the (de + el)', baseForm: 'del' },
                    { id: 'h5', text: 'comienzo', meaning: 'beginning', baseForm: 'comienzo' },
                    { id: 'h6', text: 'del', meaning: 'of the (de + el)', baseForm: 'del' },
                    { id: 'h7', text: 'fin.', meaning: 'end', baseForm: 'fin' },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'horror-panel-1-2',
          artworkImage: 'local:horror_p1_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.47,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.53,
          bubbles: [],
        },
        {
          id: 'horror-panel-1-3',
          artworkImage: 'local:horror_p1_s3',
          panelOrder: 3,
          tapZoneX: 0.5,
          tapZoneY: 0.47,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.53,
          bubbles: [
            {
              id: 'horror-bubble-1-3-1',
              type: 'thought',
              positionX: 0.1,
              positionY: 0.7,
              width: 0.8,
              height: 0.2,
              sentences: [
                {
                  id: 'horror-s2',
                  text: 'Debo encontrar un lugar donde esconderme...',
                  translation: 'I must find a place to hide...',
                  words: [
                    { id: 'h8', text: 'Debo', meaning: 'I must', baseForm: 'deber' },
                    { id: 'h9', text: 'encontrar', meaning: 'to find', baseForm: 'encontrar' },
                    { id: 'h10', text: 'un', meaning: 'a', baseForm: 'un' },
                    { id: 'h11', text: 'lugar', meaning: 'place', baseForm: 'lugar' },
                    { id: 'h12', text: 'donde', meaning: 'where', baseForm: 'donde' },
                    { id: 'h13', text: 'esconderme...', meaning: 'to hide myself', baseForm: 'esconderse' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'horror-page-2',
      pageNumber: 2,
      masterImage: 'local:horror_p2',
      panels: [
        {
          id: 'horror-panel-2-1',
          artworkImage: 'local:horror_p2_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.5,
          bubbles: [
            {
              id: 'horror-bubble-2-1-1',
              type: 'thought',
              positionX: 0.1,
              positionY: 0.05,
              width: 0.5,
              height: 0.15,
              sentences: [
                {
                  id: 'horror-s3',
                  text: 'Quizás... aquí dentro...',
                  translation: 'Maybe... in here...',
                  words: [
                    { id: 'h14', text: 'Quizás...', meaning: 'Maybe, perhaps', baseForm: 'quizás' },
                    { id: 'h15', text: 'aquí', meaning: 'here', baseForm: 'aquí' },
                    { id: 'h16', text: 'dentro...', meaning: 'inside', baseForm: 'dentro' },
                  ],
                },
              ],
            },
            {
              id: 'horror-bubble-2-1-2',
              type: 'speech',
              positionX: 0.4,
              positionY: 0.2,
              width: 0.5,
              height: 0.2,
              sentences: [
                {
                  id: 'horror-s4',
                  text: '¿No hay nadie ahí dentro?',
                  translation: 'Is there nobody in there?',
                  words: [
                    { id: 'h17', text: '¿No', meaning: 'Not (question)', baseForm: 'no' },
                    { id: 'h18', text: 'hay', meaning: 'there is/are', baseForm: 'haber' },
                    { id: 'h19', text: 'nadie', meaning: 'nobody', baseForm: 'nadie' },
                    { id: 'h20', text: 'ahí', meaning: 'there', baseForm: 'ahí' },
                    { id: 'h21', text: 'dentro?', meaning: 'inside', baseForm: 'dentro' },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'horror-panel-2-2',
          artworkImage: 'local:horror_p2_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.5,
          tapZoneWidth: 1,
          tapZoneHeight: 0.5,
          bubbles: [],
        },
      ],
    },
    {
      id: 'horror-page-3',
      pageNumber: 3,
      masterImage: 'local:horror_p3',
      panels: [
        {
          id: 'horror-panel-3-1',
          artworkImage: 'local:horror_p3_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.33,
          bubbles: [
            {
              id: 'horror-bubble-3-1-1',
              type: 'thought',
              positionX: 0.1,
              positionY: 0.05,
              width: 0.6,
              height: 0.15,
              sentences: [
                {
                  id: 'horror-s5',
                  text: 'Está oscuro aquí dentro...',
                  translation: 'It\'s dark in here...',
                  words: [
                    { id: 'h22', text: 'Está', meaning: 'It is (state)', baseForm: 'estar' },
                    { id: 'h23', text: 'oscuro', meaning: 'dark', baseForm: 'oscuro' },
                    { id: 'h24', text: 'aquí', meaning: 'here', baseForm: 'aquí' },
                    { id: 'h25', text: 'dentro...', meaning: 'inside', baseForm: 'dentro' },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'horror-panel-3-2',
          artworkImage: 'local:horror_p3_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.33,
          tapZoneWidth: 1,
          tapZoneHeight: 0.34,
          bubbles: [],
        },
        {
          id: 'horror-panel-3-3',
          artworkImage: 'local:horror_p3_s3',
          panelOrder: 3,
          tapZoneX: 0,
          tapZoneY: 0.67,
          tapZoneWidth: 1,
          tapZoneHeight: 0.33,
          bubbles: [
            {
              id: 'horror-bubble-3-3-1',
              type: 'narration',
              positionX: 0.3,
              positionY: 0.7,
              width: 0.6,
              height: 0.2,
              sentences: [
                {
                  id: 'horror-s6',
                  text: 'Esta casa ha estado vacía desde hace mucho tiempo.',
                  translation: 'This house has been empty for a long time.',
                  words: [
                    { id: 'h26', text: 'Esta', meaning: 'This (feminine)', baseForm: 'este' },
                    { id: 'h27', text: 'casa', meaning: 'house', baseForm: 'casa' },
                    { id: 'h28', text: 'ha', meaning: 'has (auxiliary)', baseForm: 'haber' },
                    { id: 'h29', text: 'estado', meaning: 'been', baseForm: 'estar' },
                    { id: 'h30', text: 'vacía', meaning: 'empty (feminine)', baseForm: 'vacío' },
                    { id: 'h31', text: 'desde', meaning: 'since, for', baseForm: 'desde' },
                    { id: 'h32', text: 'hace', meaning: 'ago, for (time)', baseForm: 'hacer' },
                    { id: 'h33', text: 'mucho', meaning: 'much, a lot', baseForm: 'mucho' },
                    { id: 'h34', text: 'tiempo.', meaning: 'time', baseForm: 'tiempo' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'horror-page-4',
      pageNumber: 4,
      masterImage: 'local:horror_p4',
      panels: [
        {
          id: 'horror-panel-4-1',
          artworkImage: 'local:horror_p4_s1',
          panelOrder: 1,
          tapZoneX: 0,
          tapZoneY: 0,
          tapZoneWidth: 1,
          tapZoneHeight: 0.35,
          bubbles: [],
        },
        {
          id: 'horror-panel-4-2',
          artworkImage: 'local:horror_p4_s2',
          panelOrder: 2,
          tapZoneX: 0,
          tapZoneY: 0.35,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.30,
          bubbles: [],
        },
        {
          id: 'horror-panel-4-3',
          artworkImage: 'local:horror_p4_s3',
          panelOrder: 3,
          tapZoneX: 0.5,
          tapZoneY: 0.35,
          tapZoneWidth: 0.5,
          tapZoneHeight: 0.30,
          bubbles: [],
        },
        {
          id: 'horror-panel-4-4',
          artworkImage: 'local:horror_p4_s3',
          panelOrder: 4,
          tapZoneX: 0,
          tapZoneY: 0.65,
          tapZoneWidth: 1,
          tapZoneHeight: 0.36,
          bubbles: [
            {
              id: 'horror-bubble-4-4-1',
              type: 'speech',
              positionX: 0.2,
              positionY: 0.1,
              width: 0.6,
              height: 0.3,
              sentences: [
                {
                  id: 'horror-s7',
                  text: '¡¡Aléjate de mí!!',
                  translation: 'Get away from me!!',
                  words: [
                    { id: 'h35', text: '¡¡Aléjate', meaning: 'Get away (imperative)', baseForm: 'alejarse' },
                    { id: 'h36', text: 'de', meaning: 'from', baseForm: 'de' },
                    { id: 'h37', text: 'mí!!', meaning: 'me', baseForm: 'mí' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
